version: '3'

services:
  mp:
    build: .
    container_name: mp-core
    restart: always
    env_file:
      - ./server-variables.env
    ports:
      - "8888:8080"
networks:
  default:
    external: true
    name: dockerpgdb_default